CREATE TABLE [dbo].[DimOpportunityLine] (
    [OpportunityLineID]         VARCHAR (100)   NOT NULL,
    [OpportunityID]             VARCHAR (20)    NOT NULL,
    [Opportunity]               VARCHAR (30)    NULL,
    [OpportunityLine]           INT             NULL,
    [OPL_AccountID]             VARCHAR (20)    NULL,
    [OPL_ACC_Name]              VARCHAR (255)   NULL,
    [OPL_Acc_Type]              VARCHAR (40)    NULL,
    [OPL_Agency_Name]           VARCHAR (255)   NULL,
    [BookingCategory]           VARCHAR (40)    NULL,
    [OPL_ItemNumber]            VARCHAR (40)    NULL,
    [OPL_Ahalogy_SE]            VARCHAR (50)    NULL,
    [CPG_AccountID]             VARCHAR (20)    NOT NULL,
    [CPG_DivisionID]            VARCHAR (20)    NOT NULL,
    [CPG_Name]                  VARCHAR (255)   NULL,
    [CPG_Division]              VARCHAR (100)   NULL,
    [Retailer_AccountID]        VARCHAR (20)    NULL,
    [Retailer_DivisionID]       VARCHAR (20)    NULL,
    [Retailer_Acc_Name]         VARCHAR (255)   NULL,
    [Retailer_Division]         VARCHAR (100)   NULL,
    [RetailerID]                INT             NOT NULL,
    [Launch_Date]               DATETIME2 (7)   NULL,
    [End_Date]                  DATETIME2 (7)   NULL,
    [ProductID]                 VARCHAR (20)    NULL,
    [CommitQuantity]            NUMERIC (18)    NULL,
    [SalePrice]                 NUMERIC (18, 5) NULL,
    [ParentAccountName]         VARCHAR (255)   NULL,
    [ProductType_ID]            INT             NULL,
    [RS_Status]                 VARCHAR (50)    NULL,
    [RS_EstimatedRevenueStatus] VARCHAR (50)    NULL,
    [BrandID]                   VARCHAR (100)   NULL,
    [NationallyFunded]          VARCHAR (5)     NULL,
    CONSTRAINT [pk_DimOpportunityLine] PRIMARY KEY CLUSTERED ([OpportunityLineID] ASC, [OpportunityID] ASC)
);

