CREATE TABLE [dbo].[DimOpportunity] (
    [OpportunityID]               VARCHAR (20)    NOT NULL,
    [Opportunity]                 VARCHAR (30)    NULL,
    [AdvertiserFullName]          VARCHAR (100)   NULL,
    [StageName]                   VARCHAR (40)    NULL,
    [ForecastCategory]            VARCHAR (40)    NULL,
    [Probability]                 INT             NULL,
    [CommissionInformation]       VARCHAR (255)   NULL,
    [OpportunityName]             VARCHAR (120)   NULL,
    [CampaignName]                VARCHAR (50)    NULL,
    [OP_AccountID]                VARCHAR (20)    NULL,
    [OP_Acc_Name]                 VARCHAR (255)   NULL,
    [OP_Acc_Type]                 VARCHAR (40)    NULL,
    [OP_DivisionID]               VARCHAR (20)    NULL,
    [OP_Division]                 VARCHAR (80)    NULL,
    [OP_AgencyID]                 VARCHAR (20)    NULL,
    [OP_Agency_Name]              VARCHAR (255)   NULL,
    [CreateDate]                  DATETIME2 (7)   NULL,
    [CreateDemandFlag]            TINYINT         NULL,
    [LastModifiedDate]            DATETIME        NULL,
    [AtRiskDetails]               VARCHAR (255)   NULL,
    [AtRiskStatus]                VARCHAR (50)    NULL,
    [DaysAtRisk]                  NUMERIC (18, 2) NULL,
    [TimeEnteredAtRisk]           DATETIME2 (7)   NULL,
    [TimeExitedAtRisk]            DATETIME2 (7)   NULL,
    [OwnerID]                     NVARCHAR (18)   NULL,
    [OwnerName]                   VARCHAR (100)   NULL,
    [OPH_FirstCloseDate]          DATETIME        NULL,
    [OPH_ClosedLostDate]          DATETIME        NULL,
    [ClosedLost_Reason]           VARCHAR (MAX)   NULL,
    [OPH_CurrentStage_Date]       DATETIME        NULL,
    [ForecastCategory_Stage_Date] DATETIME        NULL,
    [CSM]                         VARCHAR (100)   NULL,
    [DCM]                         VARCHAR (100)   NULL,
    [First_Seen_Date]             DATETIME2 (7)   NULL,
    [Closed_Date]                 DATETIME2 (7)   NULL,
    [Last_Seen_Date]              DATETIME2 (7)   NULL,
    [Won_Lost]                    VARCHAR (11)    NOT NULL,
    [time_to_close]               INT             NULL,
    [ClosedP30d]                  INT             NULL,
    [CreatedP30d]                 INT             NULL,
    [Notes]                       VARCHAR (MAX)   NULL,
    [EarliestLaunchDate]          VARCHAR (MAX)   NULL,
    [CreateDateID]                INT             NULL,
    [Derived_ActivityDate]        DATETIME        NULL,
    [Derived_ActivityDateID]      INT             NULL
);

