CREATE TABLE [dbo].[DimAccountInfo_New_06152021] (
    [CPG_AccountID]            VARCHAR (100) NOT NULL,
    [CPG_DivisionID]           VARCHAR (20)  NOT NULL,
    [RetailerID]               INT           NOT NULL,
    [ProductType_ID]           INT           NOT NULL,
    [AA_Promo_SE]              VARCHAR (100) NULL,
    [AA_SubRegion]             VARCHAR (50)  NULL,
    [AA_Region]                VARCHAR (50)  NULL,
    [RetailerVP]               VARCHAR (50)  NULL,
    [RetailerRD]               VARCHAR (50)  NULL,
    [RetailerSD]               VARCHAR (50)  NULL,
    [BD_RetailerRD]            VARCHAR (50)  NULL,
    [AA_Data_SE]               VARCHAR (50)  NULL,
    [AA_Data_SSD]              VARCHAR (50)  NULL,
    [AA_Social_SE]             VARCHAR (50)  NULL,
    [AA_Social_SSD]            VARCHAR (50)  NULL,
    [National/RetailerOnly]    VARCHAR (13)  NULL,
    [CPG/Shopper_Inv]          VARCHAR (22)  NULL,
    [CPG_AccountName]          VARCHAR (100) NULL,
    [CPG_Division]             VARCHAR (100) NULL,
    [Segments]                 VARCHAR (50)  NULL,
    [SellType]                 VARCHAR (50)  NULL,
    [CPG_PromoSE_UserID]       VARCHAR (50)  NULL,
    [Retailer_PromoSE_UserID]  VARCHAR (50)  NULL,
    [Data_PromoSE_UserID]      VARCHAR (50)  NULL,
    [Social_PromoSE_UserID]    VARCHAR (50)  NULL,
    [CPG_SSD_UserID]           VARCHAR (50)  NULL,
    [CPG_RD_UserID]            VARCHAR (50)  NULL,
    [CPG_Exception_UserID]     VARCHAR (50)  NULL,
    [Retailer_RD_UserID]       VARCHAR (50)  NULL,
    [Retailer_VP_UserID]       VARCHAR (50)  NULL,
    [Retailer_Excepion_UserID] VARCHAR (50)  NULL,
    [Social_SSD_UserID]        VARCHAR (50)  NULL,
    [Social_Exception_UserID]  VARCHAR (50)  NULL,
    [DOOH_SE]                  VARCHAR (50)  NULL,
    [DOOH_SSD]                 VARCHAR (50)  NULL,
    [DOOH_VP]                  VARCHAR (50)  NULL,
    [DOOH_SE_UserID]           VARCHAR (50)  NULL,
    [DOOH_SSD_UserID]          VARCHAR (50)  NULL,
    [DOOH_VP_UserID]           VARCHAR (50)  NULL,
    [DOOH_Exception_UserID]    VARCHAR (50)  NULL
);

