CREATE TABLE [dbo].[MDM_DAY_DIM] (
    [DATE_SID]                   BIGINT        NULL,
    [DATE_ID]                    BIGINT        NOT NULL,
    [DAY_START]                  DATETIME      NULL,
    [DAY_END]                    DATETIME      NULL,
    [DAY_CAPTION]                VARCHAR (100) NULL,
    [DAY_OF_WEEK_NUMBER]         BIGINT        NULL,
    [DAY_OF_MONTH_NUMBER]        BIGINT        NULL,
    [DAY_OF_YEAR_NUMBER]         BIGINT        NULL,
    [DAY_OF_WEEK]                VARCHAR (100) NULL,
    [LAST_DAY_SID]               BIGINT        NULL,
    [LAST_YEAR_SAME_DAY_SID]     BIGINT        NULL,
    [WEEK_SID]                   BIGINT        NULL,
    [WEEK_ID]                    BIGINT        NULL,
    [WEEK_START]                 DATETIME      NULL,
    [WEEK_END]                   DATETIME      NULL,
    [WEEK_CAPTION]               VARCHAR (100) NULL,
    [WEEK_OF_YEAR_NUMBER]        BIGINT        NULL,
    [WEEK_OF_MONTH_NUMBER]       BIGINT        NULL,
    [LAST_WEEK_SID]              BIGINT        NULL,
    [LAST_YEAR_SAME_WEEK_SID]    BIGINT        NULL,
    [MONTH_SID]                  BIGINT        NULL,
    [MONTH_ID]                   BIGINT        NULL,
    [MONTH_START]                DATETIME      NULL,
    [MONTH_END]                  DATETIME      NULL,
    [MONTH_CAPTION]              VARCHAR (100) NULL,
    [MONTH_OF_YEAR_NUMBER]       BIGINT        NULL,
    [LAST_MONTH_SID]             BIGINT        NULL,
    [LAST_YEAR_SAME_MONTH_SID]   BIGINT        NULL,
    [QUARTER_SID]                BIGINT        NULL,
    [QUARTER_ID]                 BIGINT        NULL,
    [QUARTER_START]              DATETIME      NULL,
    [QUARTER_END]                DATETIME      NULL,
    [QUARTER_CAPTION]            VARCHAR (100) NULL,
    [QUARTER_OF_YEAR_NUMBER]     BIGINT        NULL,
    [LAST_QUARTER_SID]           BIGINT        NULL,
    [LAST_YEAR_SAME_QUARTER_SID] BIGINT        NULL,
    [YEAR_SID]                   BIGINT        NULL,
    [YEAR_ID]                    BIGINT        NULL,
    [YEAR_START]                 DATETIME      NULL,
    [YEAR_END]                   DATETIME      NULL,
    [YEAR_CAPTION]               VARCHAR (100) NULL,
    [LAST_YEAR_SID]              BIGINT        NULL,
    [CAL_WEEK_SID]               BIGINT        NULL,
    [CAL_WEEK_ID]                BIGINT        NULL,
    [LAST_DAY_ID]                BIGINT        NULL,
    [LAST_YEAR_SAME_DAY_ID]      BIGINT        NULL,
    [LAST_MONTH_ID]              BIGINT        NULL,
    [LAST_QUARTER_ID]            BIGINT        NULL,
    [LAST_YEAR_SAME_QUARTER_ID]  BIGINT        NULL,
    [LAST_YEAR_SAME_MONTH_ID]    BIGINT        NULL,
    [LAST_WEEK_ID]               BIGINT        NULL,
    [LAST_YEAR_SAME_WEEK_ID]     BIGINT        NULL,
    [LAST_YEAR_ID]               BIGINT        NULL,
    [SHORT_DATE]                 DATE          NULL,
    [LAST_WEEK_DATE]             DATE          NULL,
    [LAST_WEEK_DATEID]           BIGINT        NULL,
    [LAST_YEAR_QTR_END_DATE_ID]  BIGINT        NULL,
    [LAST_QTR_END_DATE_ID]       BIGINT        NULL,
    [LAST_QTR_SAME_DAY_ID]       BIGINT        NULL,
    [MONTH_DESC]                 NVARCHAR (16) NULL,
    CONSTRAINT [DATE_ID] PRIMARY KEY CLUSTERED ([DATE_ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [IX_MDM_DAY_DIM_MONTH_ID]
    ON [dbo].[MDM_DAY_DIM]([MONTH_ID] ASC)
    INCLUDE([MONTH_START], [MONTH_END], [MONTH_CAPTION], [QUARTER_ID], [LAST_MONTH_ID], [LAST_YEAR_SAME_MONTH_ID]);

