













CREATE VIEW [dbo].[vDimDate]
AS

SELECT DATE_ID,
	SHORT_DATE AS [DATE],
	--CAST(DAY_CAPTION AS DATE) AS [DATE],
	--DATEADD(DD,-7,CAST(DAY_CAPTION AS DATE)) AS [LAST_WEEK_DATE],
	[LAST_WEEK_DATE],
	--CAST(SUBSTRING(CONVERT(VARCHAR(8),DATEADD(DD,-7,CAST(DAY_CAPTION AS DATE)),112),1,8) AS BIGINT) AS [LAST_WEEK_DATEID],
	[LAST_WEEK_DATEID],
	MONTH_ID,
	WEEK_ID,
	DAY_OF_WEEK,
	DAY_OF_WEEK_NUMBER,
	LAST_YEAR_SAME_DAY_ID,
	--CAST(SUBSTRING(CONVERT(VARCHAR(8),CAST(DATEADD(YY,-1,DAY_START) AS DATE),112),1,8) AS BIGINT)  AS LAST_YEAR_SAME_DAY_ID,
	--CASE WHEN LAST_YEAR_QTR_END_DATE_ID = 20200701  THEN 20210101 ELSE LAST_YEAR_QTR_END_DATE_ID  END AS LAST_YEAR_QTR_END_DATE_ID ,
	
	20210101 AS LAST_YEAR_QTR_END_DATE_ID,
	--CAST(SUBSTRING(CONVERT(VARCHAR(8),CAST(CONVERT(DATE,DATEADD(d, -1, DATEADD(q, DATEDIFF(q, 0, DATEADD(YEAR,-1,CAST(DAY_CAPTION AS DATE))) +1, +1))) AS DATE),112),1,8) AS BIGINT) AS LAST_YEAR_QTR_END_DATE_ID,
	LAST_QTR_END_DATE_ID,
	--CAST(SUBSTRING(CONVERT(VARCHAR(8),CAST(DATEADD(dd, -1, DATEADD(qq, DATEDIFF(qq, 0, DAY_CAPTION), 1)) AS DATE),112),1,8) AS BIGINT) AS LAST_QTR_END_DATE_ID,
	LAST_QTR_SAME_DAY_ID
	--CAST(SUBSTRING(CONVERT(VARCHAR(8),CAST(DATEADD(QQ,-1,DAY_CAPTION) AS DATE),112),1,8) AS BIGINT)  AS LAST_QTR_SAME_DAY_ID
FROM MSTRReportingDB.DBO.MDM_DAY_DIM WITH (NOLOCK)
WHERE DATE_ID >= 20160101 AND DATE_ID < 20230101

	

	--SELECT DATE_ID,CAST(DAY_CAPTION AS DATE) AS [DATE],
	--	DATEADD(DD,-7,CAST(DAY_CAPTION AS DATE)) AS [LAST_WEEK_DATE],
	--	CAST(SUBSTRING(CONVERT(VARCHAR(8),DATEADD(DD,-7,CAST(DAY_CAPTION AS DATE)),112),1,8) AS BIGINT) AS [LAST_WEEK_DATEID],
	--	MONTH_ID,WEEK_ID,DAY_OF_WEEK,DAY_OF_WEEK_NUMBER
	--	--,LAST_YEAR_SAME_DAY_ID
	--	, CAST(SUBSTRING(CONVERT(VARCHAR(8),CAST(DATEADD(YY,-1,DAY_START) AS DATE),112),1,8) AS BIGINT)  AS LAST_YEAR_SAME_DAY_ID
	--	,CAST(SUBSTRING(CONVERT(VARCHAR(8),CAST(CONVERT(DATE,DATEADD(d, -1, DATEADD(q, DATEDIFF(q, 0, DATEADD(YEAR,-1,CAST(DAY_CAPTION AS DATE))) +1, +1))) AS DATE),112),1,8) AS BIGINT) AS LAST_YEAR_QTR_END_DATE_ID
	--	,CAST(SUBSTRING(CONVERT(VARCHAR(8),CAST(DATEADD(dd, -1, DATEADD(qq, DATEDIFF(qq, 0, DAY_CAPTION), 1)) AS DATE),112),1,8) AS BIGINT) AS LAST_QTR_END_DATE_ID
	--	,CAST(SUBSTRING(CONVERT(VARCHAR(8),CAST(DATEADD(QQ,-1,DAY_CAPTION) AS DATE),112),1,8) AS BIGINT)  AS LAST_QTR_SAME_DAY_ID
	--FROM MSTRReportingDB.DBO.MDM_DAY_DIM 
	--WHERE DATE_ID >= 20160101 AND DATE_ID < 20220101









