








CREATE VIEW [dbo].[vDimEST_Rev_Month]
AS

SELECT DISTINCT 
	MONTH_ID AS EST_REV_MONTH_ID
	,MONTH_START AS EST_REV_MONTH_START
	,MONTH_END AS EST_REV_MONTH_END
	,MONTH_CAPTION AS EST_REV_MONTH_CAPTION
	,MONTH_DESC AS EST_REV_MONTH_DESC
	--,LEFT(DATENAME(MONTH,MONTH_CAPTION),3) + ' ' + RIGHT('00' + CAST(YEAR(MONTH_CAPTION) AS VARCHAR),4) AS EST_REV_MONTH_DESC
	,LAST_MONTH_ID AS EST_REV_LAST_MONTH_ID
	,LAST_YEAR_SAME_MONTH_ID AS EST_REV_LAST_YEAR_SAME_MONTH_ID
	,QUARTER_ID AS EST_REV_QUARTER_ID
FROM MSTRReportingDB.DBO.MDM_DAY_DIM WITH (NOLOCK)
WHERE DATE_ID >= 20160101 AND DATE_ID < 20230101



--SELECT DISTINCT 
--	MONTH_ID AS EST_REV_MONTH_ID
--	,MONTH_START AS EST_REV_MONTH_START
--	,MONTH_END AS EST_REV_MONTH_END
--	,MONTH_CAPTION AS EST_REV_MONTH_CAPTION
--	,LEFT(DATENAME(MONTH,MONTH_CAPTION),3) + ' ' + RIGHT('00' + CAST(YEAR(MONTH_CAPTION) AS VARCHAR),4) AS EST_REV_MONTH_DESC
--	,LAST_MONTH_ID AS EST_REV_LAST_MONTH_ID
--	,LAST_YEAR_SAME_MONTH_ID AS EST_REV_LAST_YEAR_SAME_MONTH_ID
--	,QUARTER_ID AS EST_REV_QUARTER_ID
--FROM MSTRReportingDB.DBO.MDM_DAY_DIM 
--WHERE DATE_ID >= 20160101 AND DATE_ID < 20220101








