







CREATE VIEW [dbo].[vDimEST_Rev_Week]
AS

SELECT DISTINCT WEEK_ID AS EST_REV_WEEK_ID
	,WEEK_START AS EST_REV_WEEK_START
	,WEEK_END AS EST_REV_WEEK_END
	,WEEK_OF_YEAR_NUMBER AS EST_REV_WEEK_OF_YEAR_NUMBER
	,WEEK_OF_MONTH_NUMBER AS EST_REV_WEEK_OF_MONTH_NUMBER
	,LAST_WEEK_ID AS EST_REV_LAST_WEEK_ID
	,LAST_YEAR_SAME_WEEK_ID AS EST_REV_LAST_YEAR_SAME_WEEK_ID
FROM MSTRReportingDB.DBO.MDM_DAY_DIM WITH (NOLOCK)
WHERE DATE_ID >= 20160101 AND DATE_ID < 20230101






