








CREATE VIEW [dbo].[vDimMonth]
AS


SELECT DISTINCT MONTH_ID
	,MONTH_START
	,MONTH_END
	,MONTH_CAPTION
	--,LEFT(DATENAME(MONTH,MONTH_CAPTION),3) + ' ' + RIGHT('00' + CAST(YEAR(MONTH_CAPTION) AS VARCHAR),4) AS MONTH_DESC
	,MONTH_DESC
	,LAST_MONTH_ID
	,LAST_YEAR_SAME_MONTH_ID
	,QUARTER_ID
FROM MSTRReportingDB.DBO.MDM_DAY_DIM WITH (NOLOCK)
WHERE DATE_ID >= 20160101 AND DATE_ID < 20230101


--SELECT DISTINCT MONTH_ID
--	,MONTH_START
--	,MONTH_END
--	,MONTH_CAPTION
--	,LEFT(DATENAME(MONTH,MONTH_CAPTION),3) + ' ' + RIGHT('00' + CAST(YEAR(MONTH_CAPTION) AS VARCHAR),4) AS MONTH_DESC
--	,LAST_MONTH_ID
--	,LAST_YEAR_SAME_MONTH_ID
--	,QUARTER_ID
--FROM MSTRReportingDB.DBO.MDM_DAY_DIM 
--WHERE DATE_ID >= 20160101 AND DATE_ID < 20220101







