








CREATE VIEW [dbo].[vDimEST_Rev_Quarter]
AS

SELECT DISTINCT QUARTER_ID AS EST_REV_QUARTER_ID
	,QUARTER_START AS EST_REV_QUARTER_START
	,QUARTER_END AS EST_REV_QUARTER_END
	,QUARTER_CAPTION AS EST_REV_QUARTER_CAPTION
	,QUARTER_OF_YEAR_NUMBER AS EST_REV_QUARTER_OF_YEAR_NUMBER
	,LAST_QUARTER_ID AS EST_REV_LAST_QUARTER_ID
	,LAST_YEAR_SAME_QUARTER_ID AS EST_REV_LAST_YEAR_SAME_QUARTER_ID
	,YEAR_ID AS EST_REV_YEAR_ID
FROM MSTRReportingDB.DBO.MDM_DAY_DIM WITH (NOLOCK)
WHERE DATE_ID >= 20160101 AND DATE_ID < 20230101








