











CREATE VIEW [dbo].[vDimDerivedActivity_Quarter]
AS

SELECT DISTINCT QUARTER_ID AS DerivedActivity_QUARTER_ID
	,QUARTER_START AS DerivedActivity_QUARTER_START
	,QUARTER_END AS DerivedActivity_QUARTER_END
	,QUARTER_CAPTION AS DerivedActivity_QUARTER_CAPTION
	,QUARTER_OF_YEAR_NUMBER AS DerivedActivity_QUARTER_OF_YEAR_NUMBER
	,LAST_QUARTER_ID AS DerivedActivity_LAST_QUARTER_ID
	,LAST_YEAR_SAME_QUARTER_ID AS DerivedActivity_LAST_YEAR_SAME_QUARTER_ID
	,YEAR_ID AS DerivedActivity_YEAR_ID
FROM MSTRReportingDB.DBO.MDM_DAY_DIM WITH (NOLOCK)
WHERE DATE_ID >= 20160101 AND DATE_ID < 20230101











